
CREATE TABLE CHAT(
    CHATNUM          NUMBER PRIMARY KEY,
    CHATNAME        VARCHAR2(40),
    CHATCONTENT     VARCHAR2(100),
    CHATTIME        DATE,
    IP          VARCHAR2(50)
);
COMMIT;


INSERT INTO CHAT ( CHATNUM, CHATNAME, CHATCONTENT, CHATTIME, IP )
VALUES ((SELECT NVL(MAX(CHATNUM),0)+1 FROM CHAT),'캘리' ,'ASDSA' , SYSDATE,'1231123');
INSERT INTO CHAT ( CHATNUM, CHATNAME, CHATCONTENT, CHATTIME, IP )
VALUES ((SELECT NVL(MAX(CHATNUM),0)+1 FROM CHAT),'미니' ,'ASDSA' , SYSDATE,'1231123');
INSERT INTO CHAT ( CHATNUM, CHATNAME, CHATCONTENT, CHATTIME, IP )
VALUES ((SELECT NVL(MAX(CHATNUM),0)+1 FROM CHAT),'이순신' ,'ASDSA' , SYSDATE,'1231123');
INSERT INTO CHAT ( CHATNUM, CHATNAME, CHATCONTENT, CHATTIME, IP )
VALUES ((SELECT NVL(MAX(CHATNUM),0)+1 FROM CHAT),'김시민' ,'ASDSA' , SYSDATE,'1231123');
commit;




