CREATE TABLE COUNTRYCOVIDSTATUS (
    COUNTRYNUM      NUMBER(6) PRIMARY KEY,
    NATIONNM        VARCHAR2(40),
    AREANM          VARCHAR2(20),
    NATDEFCNT       NUMBER(15),
    NATDEATHCNT     NUMBER(15),
    NATDEATHRATE    NUMBER(30, 25),
    STDDAY          DATE
);

INSERT INTO COUNTRYCOVIDSTATUS (COUNTRYNUM, NATIONNM, AREANM, NATDEFCNT, NATDEATHCNT, NATDEATHRATE, STDDAY)
VALUES ((SELECT NVL(MAX(COUNTRYNUM),0)+1 FROM COUNTRYCOVIDSTATUS), '쿠웨이트' , '중동' , 100, 1000, 0.1111, sysdate);

INSERT INTO COUNTRYCOVIDSTATUS
VALUES((SELECT NVL(MAX(COUNTRYNUM), 0) + 1 FROM COUNTRYCOVIDSTATUS), ?, ?, ?, ?, ?, ?);

DROP TABLE COUNTRYCOVIDSTATUS;