
CREATE TABLE MEMBERS (
    ID VARCHAR2(20) PRIMARY KEY,
    PASSWORD VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(150),
    NICKNAME VARCHAR2(80) UNIQUE,
    LOCSTATUS NUMBER(1) DEFAULT 0-- 저장된 주소정보
);
commit;
CREATE TABLE ADDRESS(
    ADDRESS_NUM NUMBER(32) PRIMARY KEY,
    ID VARCHAR2(20),
    NAME VARCHAR2(20), --집, 회사 등등 별칭
    ADDRESS VARCHAR2(150), -- 경기 성남시 분당구 판교역로 235
    CONSTRAINT FK_ID FOREIGN KEY(ID)
         REFERENCES MEMBERS(ID)
);


COMMIT;

DROP TABLE ADDRESS;
DROP TABLE MEM_ADDR;
DROP TABLE MEMBERS;
DROP TABLE DORO_ADDR;
DROP TABLE ADDR;
